<?php

/**
 * @file
 * Provides a gene key entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\genekey\Entity\GeneKey;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function genekey_theme() {
  return [
    'gene_key' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for gene key templates.
 *
 * Default template: gene-key.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the gene key information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gene_key(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function genekey_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish gene keys.
      $storage = \Drupal::entityTypeManager()->getStorage('gene_key');
      $gene_key_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($gene_key_ids) as $gene_key) {
        $gene_key->set('status', FALSE);
        $gene_key->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize gene keys.
      $storage = \Drupal::entityTypeManager()->getStorage('gene_key');
      $gene_key_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($gene_key_ids) as $gene_key) {
        $gene_key->setOwnerId(0);
        $gene_key->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function genekey_user_predelete(UserInterface $account) {
  // Delete gene keys.
  $storage = \Drupal::entityTypeManager()->getStorage('gene_key');
  $gene_key_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $gene_keys = $storage->loadMultiple($gene_key_ids);
  $storage->delete($gene_keys);
}
